config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    call_api
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  private

  def call_api
    recipes = HTTP.get('https://raw.githubusercontent.com/raywenderlich/recipes/master/Recipes.json').to_s
    @all_recipes = JSON.parse(recipes)
    create_recipes(@all_recipes)
  end

  def create_recipes(recipes_hash)
    recipes_hash.each do |recipe|
      ingredients = recipe['ingredients'].join(', ')
      steps = recipe['steps'].join(', ')
      Recipe.find_or_initialize_by(name: recipe['name']).update(ingredients:, steps:)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="flex flex-col">
  <div>
    <h1 class="font-bold text-4xl">Rezept Liste 🍔</h1>
    <p>Andrea's Rezeptesammlung</p>
  </div>

  <div class="flex flex-col mt-4 mb-4">
  <%= @recipes.each do |recipe|  %>
    <div class="">
      <h2 class="text-red-500 text-2xl mt-4"><%= recipe.name %></h2>
      <%= link_to "Rezept Ansehen", recipe_path(recipe)  %>
      <p><%= recipe.ingredients %></p>
      <p><%= recipe.steps %></p>
    </div>
  <% end %>
  </div>
</div>

_

app/views/recipes/show.html.erb
<div>
  <h1 >Rezept und Anleitung</h1>
  <div class="font-bold text-4xl">
    <%= @recipe.name  %>
  </div>
  <div class="font-bold text-2xl mt-6"> Zutaten:</div>
  <%= @recipe.ingredients %>
  <div class="font-bold text-2xl mt-6">  Anleitung:</div>
  <%= @recipe.steps  %>
  <div class="flex mt-6 p-2 rounded-md w-28 bg-gray-200 hover:bg-blue-400">
  <div class="mr-2">⬅️</div>
  <%= link_to "Zurück", root_path %>
  </div>
</div>